const statusPack = {
  OK_STATUS: 200,
  CREATED_STATUS: 201,
  NO_CONTENT_STATUS: 204,
  BAD_REQUEST_STATUS: 400,
  UNAUTHORIZED_STATUS: 401,
  NOT_FOUND_STATUS: 404,
  CONFLICT_STATUS: 409,
  UNPROCESSABLE_ENTITY: 422,
};

export = statusPack;